{{- if and .Values.plugins.enabled .Values.plugins.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "posthog.fullname" . }}-plugins
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations:
    autoscaling.alpha.kubernetes.io/behavior: {{ toJson .Values.plugins.hpa.behavior | quote }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "posthog.fullname" . }}-plugins
  minReplicas: {{ .Values.plugins.hpa.minpods }}
  maxReplicas: {{ .Values.plugins.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.plugins.hpa.cputhreshold }}
{{- end }}
