name: Bump chart version

on:
  pull_request:
    types: [closed]

jobs:
  release:
    name: Bump version based on PR label
    runs-on: ubuntu-20.04
    # Please do not remove the first if condition as without
    # it might lead 3rd party users to run this workflow
    # with untrusted inputs.
    if: |
      github.repository == 'PostHog/charts-clickhouse' &&
      github.event.pull_request.merged &&
      (
          contains(github.event.pull_request.labels.*.name, 'bump patch')
          || contains(github.event.pull_request.labels.*.name, 'bump minor')
          || contains(github.event.pull_request.labels.*.name, 'bump major')
      )


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect version bump type
        id: bump-type
        run: |
            BUMP_TYPE=null
            if [[ $BUMP_PATCH_PRESENT == 'true' ]]; then
                BUMP_TYPE=patch
            fi
            if [[ $BUMP_MINOR_PRESENT == 'true' ]]; then
                BUMP_TYPE=minor
            fi
            if [[ $BUMP_MAJOR_PRESENT == 'true' ]]; then
                BUMP_TYPE=major
            fi
            echo "::set-output name=bump-type::$BUMP_TYPE"
        env:
            BUMP_PATCH_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'bump patch') }}
            BUMP_MINOR_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'bump minor') }}
            BUMP_MAJOR_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'bump major') }}

      - name: Determine new version
        id: new-version
        if: steps.bump-type.outputs.bump-type != 'null'
        run: |
            OLD_VERSION=$(cat charts/posthog/Chart.yaml | sed -n 's/^version: \(.*\)$/\1/p')
            NEW_VERSION=$(npx semver $OLD_VERSION -i ${{ steps.bump-type.outputs.bump-type }})
            echo "::set-output name=new-version::$NEW_VERSION"

      - name: Install Helm
        uses: azure/setup-helm@v1
        if: steps.bump-type.outputs.bump-type != 'null'
        with:
          version: v3.7.1

      - name: Update version in charts/posthog/Chart.yaml and update Chart.lock
        if: steps.bump-type.outputs.bump-type != 'null'
        run: |
          sed -i 's/^version: \(.*\)$/version: ${{ steps.new-version.outputs.new-version }}/g' charts/posthog/Chart.yaml
          cat charts/posthog/Chart.yaml
          helm dependency update charts/posthog/

      - name: Commit bump
        if: steps.bump-type.outputs.bump-type != 'null'
        uses: EndBug/add-and-commit@v7
        with:
            branch: ${{ github.event.pull_request.base.ref }}
            message: 'Bump version to ${{ steps.new-version.outputs.new-version }}'
