# This workflow handles deploying a branch to the pull request cluster, for
# testing purposes. It is locked down so that it can only be used by people who
# are a member of the PostHog Github org

name: PR - Preview Deploy

on:
  issue_comment: # github has PRs as a special type of issue
    types: [created]

jobs:
  commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@17f29510f1bf987b916c8cbb451566a56eed23f1
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2 # no way of getting the correct ref from the issue event, hence the below
        if: steps.check.outputs.has-permission && ${{ github.event.comment.body == '@deploy'}} # looks like this needs to go on every step. meh.

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }} # github cli is pre installed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check.outputs.has-permission && ${{ github.event.comment.body == '@deploy'}}

      - name: Declare variables that we can share across steps
        id: vars
        run: |
          GIT_SHORT="$(git rev-parse --short HEAD)"
          echo "::set-output name=git_short::${GIT_SHORT}"
          echo "::set-output name=fqdn_record::${GIT_SHORT}.posthog.cc"
        if: steps.check.outputs.has-permission && ${{ github.event.comment.body == '@deploy'}}

      - name: Install PostHog using the Helm chart
        id: helm_install
        run: |
          helm upgrade --install \
            -f ci/values/pr/values.yaml \
            --set ingress.hostname=${{ steps.vars.outputs.fqdn_record }}
            --timeout 30m \
            --create-namespace \
            --namespace pr-${{ steps.vars.outputs.git_short }} \
            posthog ./charts/posthog \
            --wait \
            --wait-for-jobs 
        if: steps.check.outputs.has-permission && ${{ github.event.comment.body == '@deploy'}}
